// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2R2ytAsAqR6hqQNDpjHQ41NvRVmgCNhk',
    appId: '1:938362188003:android:3305f1b9184235d63815d6',
    messagingSenderId: '938362188003',
    projectId: 'fir-flutter-codelab-ec9bb',
    storageBucket: 'fir-flutter-codelab-ec9bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArYHzSEkJ441n4QMoV52A4GcpjmO8uPUQ',
    appId: '1:938362188003:ios:e79bc2db4e286bb73815d6',
    messagingSenderId: '938362188003',
    projectId: 'fir-flutter-codelab-ec9bb',
    storageBucket: 'fir-flutter-codelab-ec9bb.appspot.com',
    iosClientId: '938362188003-q7gruror1v7rv33ahqaejq18v8nvjqre.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
